on:
    workflow_call:
      inputs:
        forRelease:
          description: "Run for release?"
          required: true
          type: boolean

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@502226b17e3e242e4befd0a45690fcbb27dd1373 # v6.0.3
        with:
          tag_prefix: ""
          version_format: "${major}.${minor}.${patch}${{ !inputs.forRelease && '-preview${increment}' || '' }}"
          search_commit_body: true

      - name: Setup dotnet from global.json
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
        with:
          global-json-file: global.json

      - name: Check formatting
        run: dotnet format --verify-no-changes

      - name: Build and Pack
        run: dotnet build -c Release -p:Version=${{ steps.version.outputs.version}}

      - name: Upload package artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: packages
          path: "**/*.nupkg"
